// Generated by CoffeeScript 1.12.4
(function() {
  var Launchpad, LaunchpadRouter;

  LaunchpadRouter = require('./app/js/LaunchpadRouter');

  module.exports = Launchpad = {
    router: LaunchpadRouter
  };

}).call(this);
